# Generated by Django 4.0.1 on 2022-01-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_HOST', models.CharField(max_length=128)),
                ('EMAIL_PORT', models.IntegerField()),
                ('EMAIL_HOST_USER', models.EmailField(max_length=254)),
                ('EMAIL_HOST_PASSWORD', models.CharField(max_length=254)),
            ],
        ),
    ]
